DROP DATABASE IF EXISTS oficina_mecanica;

CREATE DATABASE oficina_mecanica;

USE oficina_mecanica;

CREATE TABLE CLIENTE (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(100) NOT NULL,
    CPF_CLIENTE VARCHAR(14) UNIQUE,
    TELEFONE_CLIENTE VARCHAR(15),
    EMAIL VARCHAR(100),
    ENDERECO VARCHAR(255)
);

CREATE TABLE FUNCIONARIO (
    ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_FUNCIONARIO VARCHAR(100) NOT NULL,
    CPF_FUNCIONARIO VARCHAR(14) UNIQUE NOT NULL,
    TELEFONE_FUNCIONARIO VARCHAR(15),
    ESPECIALIDADE VARCHAR(150)
);

CREATE TABLE SERVICO (
    ID_SERVICO INT AUTO_INCREMENT PRIMARY KEY,
    MAO_DE_OBRA DECIMAL(10,2) NOT NULL,
    NOME_SERVICO VARCHAR(100) NOT NULL,
    TEMPO TIME,
    DESCRICAO_SERVICO TEXT,
    ESPECIALIDADE VARCHAR(150)
);

CREATE TABLE VEICULO (
    ID_VEICULO INT AUTO_INCREMENT PRIMARY KEY,
    MODELO VARCHAR(50) NOT NULL,
    MARCA VARCHAR(50) NOT NULL,
    ID_CLIENTE INT NOT NULL,
    ANO INT,
    PLACA VARCHAR(10) UNIQUE NOT NULL,
    FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE PECAS (
    ID_PECA INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PECA VARCHAR(100) NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL,
    QUANTIDADE INT,
    DESCRICAO_PECA TEXT,
    FABRICANTE VARCHAR(100)
);

-- Tabela OS com STATUS incluído
CREATE TABLE OS (
    ID_OS INT AUTO_INCREMENT PRIMARY KEY,
    ID_VEICULO INT NOT NULL,
    DATA_ABERTURA DATE NOT NULL,
    STATUS VARCHAR(50) DEFAULT 'Aberta',
    DATA_CONCLUSAO DATE,
    OBS TEXT,
    TOTAL DECIMAL(10,2),
    FOREIGN KEY(ID_VEICULO) REFERENCES VEICULO(ID_VEICULO)
);

CREATE TABLE ATENDE (
    ID_OS INT NOT NULL,
    ID_FUNCIONARIO INT NOT NULL,
    PRIMARY KEY(ID_OS, ID_FUNCIONARIO),
    FOREIGN KEY(ID_OS) REFERENCES OS(ID_OS),
    FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO)
);

CREATE TABLE UTILIZA (
    ID_OS INT NOT NULL,
    ID_PECA INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    PRIMARY KEY(ID_OS, ID_PECA),
    FOREIGN KEY(ID_OS) REFERENCES OS(ID_OS),
    FOREIGN KEY(ID_PECA) REFERENCES PECAS(ID_PECA)
);

CREATE TABLE REALIZA (
    ID_OS INT NOT NULL,
    ID_SERVICO INT NOT NULL,
    PRIMARY KEY(ID_OS, ID_SERVICO),
    FOREIGN KEY(ID_OS) REFERENCES OS(ID_OS),
    FOREIGN KEY(ID_SERVICO) REFERENCES SERVICO(ID_SERVICO)
);

-- Inserir dados de exemplo
INSERT INTO CLIENTE (NOME_CLIENTE, CPF_CLIENTE, TELEFONE_CLIENTE, EMAIL, ENDERECO) VALUES
('João Silva', '123.456.789-00', '(11) 99999-9999', 'joao@email.com', 'Rua A, 123'),
('Maria Santos', '987.654.321-00', '(11) 98888-8888', 'maria@email.com', 'Rua B, 456');

INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, CPF_FUNCIONARIO, TELEFONE_FUNCIONARIO, ESPECIALIDADE) VALUES
('Carlos Mecânico', '111.222.333-44', '(11) 97777-7777', 'Motor'),
('Ana Eletricista', '555.666.777-88', '(11) 96666-6666', 'Elétrica');

INSERT INTO SERVICO (NOME_SERVICO, MAO_DE_OBRA, TEMPO, DESCRICAO_SERVICO, ESPECIALIDADE) VALUES
('Troca de óleo', 150.00, '01:00:00', 'Troca de óleo do motor', 'Manutenção'),
('Alinhamento', 120.00, '00:45:00', 'Alinhamento e balanceamento', 'Suspensão'),
('Freios', 200.00, '02:00:00', 'Troca de pastilhas de freio', 'Freios');

INSERT INTO PECAS (NOME_PECA, PRECO, QUANTIDADE, DESCRICAO_PECA, FABRICANTE) VALUES
('Filtro de óleo', 25.00, 50, 'Filtro de óleo para motor', 'Bosch'),
('Pastilha de freio', 120.00, 30, 'Pastilha de freio dianteira', 'TRW'),
('Bateria 60Ah', 350.00, 20, 'Bateria automotiva 60Ah', 'Moura');

INSERT INTO VEICULO (MODELO, MARCA, ID_CLIENTE, ANO, PLACA) VALUES
('Civic', 'Honda', 1, 2020, 'ABC-1234'),
('Corolla', 'Toyota', 2, 2019, 'XYZ-5678');
INSERT INTO CLIENTE (NOME_CLIENTE, CPF_CLIENTE, TELEFONE_CLIENTE, EMAIL, ENDERECO) VALUES
('João Silva', '123.456.789-00', '(11) 99999-8888', 'joao@email.com', 'Rua A, 100'),
('Maria Santos', '987.654.321-00', '(11) 97777-6666', 'maria@email.com', 'Rua B, 200'),
('Carlos Oliveira', '456.789.123-00', '(11) 95555-4444', 'carlos@email.com', 'Rua C, 300');

INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, CPF_FUNCIONARIO, TELEFONE_FUNCIONARIO, ESPECIALIDADE) VALUES
('Mecânico 1', '111.222.333-44', '(11) 91111-1111', 'Injeção Eletrônica'),
('Mecânico 2', '222.333.444-55', '(11) 92222-2222', 'Motor'),
('Mecânico 3', '333.444.555-66', '(11) 93333-3333', 'Suspensão'),
('Carlos', '444.555.666-77', '(11) 94444-4444', 'Elétrica');

INSERT INTO SERVICO (MAO_DE_OBRA, NOME_SERVICO, TEMPO, DESCRICAO_SERVICO, ESPECIALIDADE) VALUES
(150.00, 'Troca de óleo', '01:00:00', 'Troca de óleo do motor', 'Motor'),
(300.00, 'Alinhamento', '01:30:00', 'Alinhamento e balanceamento', 'Suspensão'),
(500.00, 'Reparo injeção', '02:30:00', 'Reparo sistema injeção', 'Injeção Eletrônica'),
(200.00, 'Troca de pastilhas', '01:15:00', 'Troca pastilhas de freio', 'Freios');

INSERT INTO VEICULO (MODELO, MARCA, ID_CLIENTE, ANO, PLACA) VALUES
('Fiesta', 'Ford', 1, 2020, 'ABC-1234'),
('Gol', 'Volkswagen', 2, 2019, 'DEF-5678'),
('Civic', 'Honda', 3, 2021, 'GHI-9012'),
('Uno', 'Fiat', 1, 2018, 'JKL-3456'),
('Focus', 'Ford', 2, 2022, 'MNO-7890');

INSERT INTO PECAS (NOME_PECA, PRECO_CUSTO, PRECO_VENDA, QUANTIDADE, DESCRICAO_PECA, FABRICANTE) VALUES
('Filtro de Óleo', 15.00, 30.00, 10, 'Filtro de óleo do motor', 'Bosch'),
('Pastilha de Freio', 80.00, 150.00, 5, 'Pastilha de freio dianteira', 'Bosch'),
('Vela de Ignição', 20.00, 45.00, 20, 'Vela de ignição', 'NGK'),
('Filtro de Ar', 25.00, 50.00, 3, 'Filtro de ar do motor', 'Mann'),
('Sensor de Oxigênio', 150.00, 300.00, 8, 'Sensor O2', 'Bosch');

INSERT INTO OS (ID_VEICULO, DATA_ABERTURA, DATA_CONCLUSAO, STATUS, OBS, TOTAL) VALUES
(1, '2024-01-15', '2024-01-20', 'Concluída', 'Troca de óleo completa', 180.00),
(2, '2024-02-10', '2024-02-12', 'Concluída', 'Alinhamento feito', 300.00),
(3, '2024-02-20', NULL, 'Em Execução', 'Aguardando peça', NULL),
(4, '2024-03-01', NULL, 'Aguardando Peça', 'Sem peça no estoque', NULL),
(1, '2024-03-05', NULL, 'Em Execução', 'Segunda visita', NULL);

INSERT INTO OS_MECANICO (ID_OS, ID_FUNCIONARIO) VALUES
(1, 1), (2, 2), (3, 3), (4, 1), (5, 4), (3, 4);

INSERT INTO OS_PECAS (ID_OS, ID_PECA, QUANTIDADE_USADA, PRECO_UNITARIO_COBRADO) VALUES
(1, 1, 1, 30.00), (1, 3, 4, 45.00), (4, 2, 2, 150.00), (3, 5, 1, 300.00);

INSERT INTO OS_SERVICO (ID_OS, ID_SERVICO, PRECO_COBRADO) VALUES
(1, 1, 150.00), (2, 2, 300.00), (3, 3, 500.00), (4, 4, 200.00);

-- Exercicios

-- 1. SELECT 

-- 1.1
SELECT * FROM VEICULO WHERE MARCA = 'Ford';

-- 1.2
SELECT DISTINCT C.* 
FROM CLIENTE C
INNER JOIN VEICULO V ON C.ID_CLIENTE = V.ID_CLIENTE
INNER JOIN OS O ON V.ID_VEICULO = O.ID_VEICULO
WHERE O.DATA_ABERTURA >= DATE_SUB(CURDATE(), INTERVAL 6 MONTH);

-- 1.3
SELECT * FROM FUNCIONARIO WHERE ESPECIALIDADE = 'Injeção Eletrônica';

-- 1.4
SELECT * FROM OS WHERE STATUS = 'Aguardando Peça';

-- 1.5
SELECT * FROM PECAS WHERE QUANTIDADE < 5;

-- 1.6
SELECT V.* 
FROM VEICULO V
WHERE (SELECT COUNT(*) FROM OS WHERE ID_VEICULO = V.ID_VEICULO) > 1;

-- 1.7
SELECT O.* 
FROM OS O
INNER JOIN OS_MECANICO OM ON O.ID_OS = OM.ID_OS
WHERE OM.ID_FUNCIONARIO = 3;

-- (Desafio)
SELECT NOME_PECA, PRECO_VENDA FROM PECAS WHERE PRECO_CUSTO > 200.00;

-- 2. UPDATE 

-- 2.1 - 
UPDATE PECAS 
SET PRECO_VENDA = PRECO_VENDA * 1.05 
WHERE FABRICANTE = 'Bosch' AND ID_PECA > 0;

-- 2.2
UPDATE OS 
SET STATUS = 'Concluída' 
WHERE ID_OS = 105 AND ID_OS > 0;

-- 2.3
UPDATE OS 
SET DATA_CONCLUSAO = CURDATE(), STATUS = 'Concluída' 
WHERE STATUS = 'Em Execução' 
AND DATA_ABERTURA < DATE_SUB(CURDATE(), INTERVAL 30 DAY)
AND ID_OS > 0;

-- (Desafio)
UPDATE PECAS 
SET QUANTIDADE = QUANTIDADE * 2 
WHERE ID_PECA = 20 AND ID_PECA > 0;

-- 3. ALTER TABLE (Modificação da Estrutura)

 -- 3.1  
 ALTER TABLE CLIENTE ADD COLUMN EMAIL VARCHAR(100);

-- 3.2 
 ALTER TABLE FUNCIONARIO MODIFY COLUMN ESPECIALIDADE VARCHAR(150);

-- 3.3
ALTER TABLE OS DROP COLUMN diagnostico_entrada;

-- (Desafio)
ALTER TABLE PECAS ADD CONSTRAINT CHK_PRECO CHECK (PRECO_VENDA >= PRECO_CUSTO);

-- 4. JOIN 

-- 4.1
SELECT O.ID_OS, C.NOME_CLIENTE, V.PLACA, O.DATA_ABERTURA
FROM OS O
INNER JOIN VEICULO V ON O.ID_VEICULO = V.ID_VEICULO
INNER JOIN CLIENTE C ON V.ID_CLIENTE = C.ID_CLIENTE;

-- 4.2
SELECT P.NOME_PECA, OP.QUANTIDADE_USADA
FROM OS_PECAS OP
INNER JOIN PECAS P ON OP.ID_PECA = P.ID_PECA
WHERE OP.ID_OS = 50;

-- 4.3
SELECT F.NOME_FUNCIONARIO
FROM OS_MECANICO OM
INNER JOIN FUNCIONARIO F ON OM.ID_FUNCIONARIO = F.ID_FUNCIONARIO
WHERE OM.ID_OS = 75;

-- (Desafio)
SELECT V.PLACA, V.MODELO, C.NOME_CLIENTE
FROM VEICULO V
INNER JOIN CLIENTE C ON V.ID_CLIENTE = C.ID_CLIENTE;

-- 5. INNER JOIN 

-- 5.1
SELECT DISTINCT V.PLACA, V.MODELO
FROM VEICULO V
INNER JOIN OS O ON V.ID_VEICULO = O.ID_VEICULO
WHERE O.STATUS = 'Em Execução';

-- 5.2
SELECT DISTINCT C.NOME_CLIENTE
FROM CLIENTE C
INNER JOIN VEICULO V ON C.ID_CLIENTE = V.ID_CLIENTE
WHERE V.MARCA = 'Volkswagen';

-- 5.3
SELECT DISTINCT F.NOME_FUNCIONARIO
FROM FUNCIONARIO F
INNER JOIN OS_MECANICO OM ON F.ID_FUNCIONARIO = OM.ID_FUNCIONARIO;

-- (Desafio)
SELECT DISTINCT S.NOME_SERVICO
FROM SERVICO S
INNER JOIN OS_SERVICO OS ON S.ID_SERVICO = OS.ID_SERVICO;

-- 6. LEFT JOIN 

-- 6.1
SELECT C.*, O.ID_OS
FROM CLIENTE C
LEFT JOIN VEICULO V ON C.ID_CLIENTE = V.ID_CLIENTE
LEFT JOIN OS O ON V.ID_VEICULO = O.ID_VEICULO;

-- 6.2
SELECT F.NOME_FUNCIONARIO, COUNT(OM.ID_OS) AS QTD_OS
FROM FUNCIONARIO F
LEFT JOIN OS_MECANICO OM ON F.ID_FUNCIONARIO = OM.ID_FUNCIONARIO
GROUP BY F.ID_FUNCIONARIO, F.NOME_FUNCIONARIO;

-- 6.3
SELECT P.NOME_PECA, SUM(COALESCE(OP.QUANTIDADE_USADA, 0)) AS TOTAL_VENDIDO
FROM PECAS P
LEFT JOIN OS_PECAS OP ON P.ID_PECA = OP.ID_PECA
GROUP BY P.ID_PECA, P.NOME_PECA;

-- (Desafio)
SELECT V.PLACA, V.MODELO, MAX(O.DATA_ABERTURA) AS ULTIMA_OS
FROM VEICULO V
LEFT JOIN OS O ON V.ID_VEICULO = O.ID_VEICULO
GROUP BY V.ID_VEICULO, V.PLACA, V.MODELO;

-- 7. RIGHT JOIN 

-- 7.1
SELECT O.ID_OS, C.NOME_CLIENTE
FROM CLIENTE C
RIGHT JOIN VEICULO V ON C.ID_CLIENTE = V.ID_CLIENTE
RIGHT JOIN OS O ON V.ID_VEICULO = O.ID_VEICULO;

-- 7.2
SELECT S.NOME_SERVICO, OS.ID_OS
FROM SERVICO S
LEFT JOIN OS_SERVICO OS ON S.ID_SERVICO = OS.ID_SERVICO;

-- 7.3
SELECT OM.*, F.NOME_FUNCIONARIO
FROM OS_MECANICO OM
INNER JOIN FUNCIONARIO F ON OM.ID_FUNCIONARIO = F.ID_FUNCIONARIO;

-- (Desafio)
SELECT O.*, V.PLACA, V.MODELO
FROM OS O
RIGHT JOIN VEICULO V ON O.ID_VEICULO = V.ID_VEICULO;

-- 8. Subconsultas 

-- 8.1
SELECT C.* FROM CLIENTE C
WHERE (SELECT COUNT(*) FROM VEICULO V 
       INNER JOIN OS O ON V.ID_VEICULO = O.ID_VEICULO 
       WHERE V.ID_CLIENTE = C.ID_CLIENTE) > 3;

-- 8.2
SELECT P.NOME_PECA FROM PECAS P
WHERE P.ID_PECA IN (
    SELECT OP.ID_PECA FROM OS_PECAS OP
    WHERE OP.ID_OS IN (
        SELECT OM.ID_OS FROM OS_MECANICO OM
        WHERE OM.ID_FUNCIONARIO = 4
    )
);

-- 8.3
SELECT V.PLACA, V.MODELO FROM VEICULO V
WHERE V.ID_VEICULO NOT IN (SELECT DISTINCT ID_VEICULO FROM OS);

-- (Desafio)
SELECT S.NOME_SERVICO FROM SERVICO S
WHERE S.MAO_DE_OBRA > (SELECT AVG(MAO_DE_OBRA) FROM SERVICO);

-- 9. Agregação (SUM, COUNT, AVG, GROUP BY)

-- 9.0 
SELECT 
    (SELECT COALESCE(SUM(PRECO_COBRADO), 0) FROM OS_SERVICO WHERE ID_OS = 100) +
    (SELECT COALESCE(SUM(PRECO_UNITARIO_COBRADO * QUANTIDADE_USADA), 0) 
     FROM OS_PECAS WHERE ID_OS = 100) AS FATURAMENTO_TOTAL;

-- 9.0 
SELECT AVG(DATEDIFF(DATA_CONCLUSAO, DATA_ABERTURA)) AS TEMPO_MEDIO_DIAS
FROM OS WHERE DATA_CONCLUSAO IS NOT NULL;

-- 9.1.1 
SELECT COUNT(*) AS TOTAL_VEICULOS FROM VEICULO;

-- 9.1.2 
SELECT SUM(QUANTIDADE * PRECO_CUSTO) AS VALOR_INVENTARIO FROM PECAS;

-- 9.1.3 
SELECT AVG(MAO_DE_OBRA) AS MEDIA_MAO_OBRA FROM SERVICO;

-- 9.2.1 
SELECT MARCA, COUNT(*) AS QUANTIDADE FROM VEICULO GROUP BY MARCA;

-- 9.2.2 
SELECT MONTH(DATA_ABERTURA) AS MES, COUNT(*) AS TOTAL_OS 
FROM OS GROUP BY MONTH(DATA_ABERTURA);

-- 9.2.3 
SELECT STATUS, COUNT(*) AS QUANTIDADE FROM OS GROUP BY STATUS;

-- 9.3.1 
SELECT COUNT(*) AS OS_CONCLUIDAS FROM OS WHERE STATUS = 'Concluída';

-- 9.3.2 
SELECT 
    SUM(OS_S.PRECO_COBRADO) + SUM(OP.PRECO_UNITARIO_COBRADO * OP.QUANTIDADE_USADA) AS FATURAMENTO_FIAT
FROM OS O
INNER JOIN VEICULO V ON O.ID_VEICULO = V.ID_VEICULO
LEFT JOIN OS_SERVICO OS_S ON O.ID_OS = OS_S.ID_OS
LEFT JOIN OS_PECAS OP ON O.ID_OS = OP.ID_OS
WHERE V.MARCA = 'Fiat' AND O.DATA_ABERTURA >= DATE_SUB(CURDATE(), INTERVAL 1 YEAR);

-- 9.3.3 
SELECT AVG(MAO_DE_OBRA) AS MEDIA_MOTOR FROM SERVICO WHERE ESPECIALIDADE = 'Motor';

-- 9.4.1 
SELECT V.ID_CLIENTE
FROM OS O
INNER JOIN VEICULO V ON O.ID_VEICULO = V.ID_VEICULO
INNER JOIN OS_SERVICO OS_S ON O.ID_OS = OS_S.ID_OS
INNER JOIN OS_PECAS OP ON O.ID_OS = OP.ID_OS
GROUP BY V.ID_CLIENTE
HAVING SUM(OS_S.PRECO_COBRADO) + SUM(OP.PRECO_UNITARIO_COBRADO * OP.QUANTIDADE_USADA) > 5000;

-- 9.4.2 
SELECT ID_PECA, SUM(QUANTIDADE_USADA) AS TOTAL_VENDIDO
FROM OS_PECAS 
GROUP BY ID_PECA
HAVING SUM(QUANTIDADE_USADA) > 100;

-- 9.4.3 
SELECT F.ESPECIALIDADE, COUNT(DISTINCT OM.ID_OS) AS TOTAL_OS
FROM FUNCIONARIO F
INNER JOIN OS_MECANICO OM ON F.ID_FUNCIONARIO = OM.ID_FUNCIONARIO
GROUP BY F.ESPECIALIDADE
HAVING COUNT(DISTINCT OM.ID_OS) > 20;

-- (Desafio) 
SELECT F.NOME_FUNCIONARIO, COUNT(OM.ID_OS) AS TOTAL_OS
FROM FUNCIONARIO F
INNER JOIN OS_MECANICO OM ON F.ID_FUNCIONARIO = OM.ID_FUNCIONARIO
GROUP BY F.ID_FUNCIONARIO, F.NOME_FUNCIONARIO
ORDER BY TOTAL_OS DESC
LIMIT 1;

-- 10. Indexação

-- 10.1 
CREATE INDEX idx_veiculo_placa ON VEICULO(PLACA);

-- 10.2 
CREATE INDEX idx_os_id_veiculo ON OS(ID_VEICULO);

-- (Desafio) Explicação sobre índice composto:
-- Um índice composto na chave primária de OS_PECAS (id_os, id_peca) é mais eficiente
-- porque otimiza consultas que filtram por ambas as colinas simultaneamente.
-- Ele organiza os dados primeiro por id_os e depois por id_peca dentro de cada id_os.
-- Para criar um índice composto (já existe como PRIMARY KEY):
-- CREATE INDEX idx_os_pecas_composto ON OS_PECAS(ID_OS, ID_PECA);