-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE CLIENTE (
ID_CLIENTE INT AUTO INCREMENT PRIMARY KEY PRIMARY KEY,
NOME_CLIENTE VARCHAR(100) NOT NULL,
CPF_CLIENTE VARCHAR(14) UNIQUE,
TELEFONE_CLIENTE VARCHAR(15),
EMAIL VARCHAR(100),
ENDERECO VARCHAR(255)
)

CREATE TABLE FUNCIONÁRIO (
ID_FUNCIONARIO INT AUTO INCREMENT PRIMARY KEY PRIMARY KEY,
NOME_FUNCIONARIO VARCHAR(100) NOT NULL,
CPF_FUNCIONARIO VARCHAR(14) UNIQUE NOT NULL,
TELEFONE_FUNCIONARIO VARCHAR(15)
)

CREATE TABLE SERVICO (
ID_SERVICO INT AUTO INCREMENT PRIMARY KEY PRIMARY KEY,
MAO_DE_OBRA DECIMA(10,2) NOT NULL,
NOME_SERVICO VARCHAR(100) NOT NULL,
TEMPO TIME,
DESCRICAO_SERVICO TEXT
)

CREATE TABLE VEICULO (
ID_VEICULO Texto(1) PRIMARY KEY,
MODELO VARCHAR(50) NOT NULL,
MARCA VARCHAR(50) NOT NULL,
ID_CLIENTE INT NOT NULL,
ANO INT,
PLACA VARCHAR(10) UNIQUE NOT NULL,
-- Erro: nome do campo duplicado nesta tabela!
ID_CLIENTE INT AUTO INCREMENT PRIMARY KEY,
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
)

CREATE TABLE PECAS (
ID_PECA INT AUTO INCREMENT PRIMARY KEY,
NOME_PECA VARCHAR(100) NOT NULL,
PRECO DECIMAL(10,2) NOT NULL,
QUANTIDADE INT,
DESCRICAO_PECA TEXT,
PRIMARY KEY(ID_PECA,NOME_PECA)
)

CREATE TABLE OS (
DATA_ABERTURA DATE,
ID_OS INT AUTO INCREMENT PRIMARY KEY PRIMARY KEY,
ID_VEICULO INT NOT NULL,
DATA_CONCLUSAO DATE,
OBS TEXT,
TOTAL DECIMAL(10,2) NOT NULL,
-- Erro: nome do campo duplicado nesta tabela!
ID_VEICULO Texto(1),
FOREIGN KEY(ID_VEICULO) REFERENCES VEICULO (ID_VEICULO)
)

CREATE TABLE ATENDE (
ID_OS INT AUTO INCREMENT PRIMARY KEY,
ID_FUNCIONARIO INT AUTO INCREMENT PRIMARY KEY,
FOREIGN KEY(ID_OS) REFERENCES OS (ID_OS),
FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONÁRIO (ID_FUNCIONARIO)
)

CREATE TABLE UTILIZA (
ID_PECA INT AUTO INCREMENT PRIMARY KEY,
NOME_PECA VARCHAR(100) NOT NULL,
ID_OS INT AUTO INCREMENT PRIMARY KEY,
FOREIGN KEY(NOME_PECA,,) REFERENCES PECAS (ID_PECA,NOME_PECA),
FOREIGN KEY(ID_OS) REFERENCES OS (ID_OS)
)

CREATE TABLE REALIZA (
ID_OS INT AUTO INCREMENT PRIMARY KEY,
ID_SERVICO INT AUTO INCREMENT PRIMARY KEY,
FOREIGN KEY(ID_OS) REFERENCES OS (ID_OS)/*falha: chave estrangeira*/
)

